# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitbrag < Formula
  desc "A terminal tool that outputs git stats for local git repositories"
  homepage "https://github.com/radulucut/gitbrag"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/radulucut/gitbrag/releases/download/v0.1.1/gitbrag_Darwin_x86_64.tar.gz"
      sha256 "91ac031e4826f3247f563f452fabe6ad82aba30beeeaa68cb9baf3adb17c55de"

      def install
        bin.install "gitbrag"
      end
    end
    on_arm do
      url "https://github.com/radulucut/gitbrag/releases/download/v0.1.1/gitbrag_Darwin_arm64.tar.gz"
      sha256 "07a31ca74e14c1783d4dfabd4f3aae5d12eb9c0b21bbc84741e2ed61abf67b9c"

      def install
        bin.install "gitbrag"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/radulucut/gitbrag/releases/download/v0.1.1/gitbrag_Linux_x86_64.tar.gz"
        sha256 "4d611dc1a0f6e1ce9dafb19de072b609933d97e6f60c232956f2cfe9105a31ac"

        def install
          bin.install "gitbrag"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/radulucut/gitbrag/releases/download/v0.1.1/gitbrag_Linux_arm64.tar.gz"
        sha256 "62dc8cfe67f36578141f04eb6512a1d9246dacb9c8a9174646e9769981dd4bdb"

        def install
          bin.install "gitbrag"
        end
      end
    end
  end
end
